values:
  Right settings/FOV: 16.8116
  Right settings/Vertical shift Parameter: 0.9333
  Right settings/Horizontal Shift Parameter: 0.6377
  Right settings/Viewpoint Y: 2.0000
  Right settings/Viewpoint X: 0.0000
  Right settings/Viewpoint Z: 40.9300
  Left settings/FOV: 18.1712
  Left settings/Vertical shift Parameter: 0.8587
  Left settings/Horizontal Shift Parameter: -0.5978
