values:
  Right Canvas/FOV: 30.0000
  Right Canvas/Horizontal Shift Parameter: 0.5000
  Right Canvas/Vertical shift Parameter: 0.0000
  Left Canvas/Vertical shift Parameter: 0.0000
  Left Canvas/Horizontal Shift Parameter: -0.5000
  Left Canvas/FOV: 30.0000
  Right Canvas/Viewpoint Z: 40.9300
  Right Canvas/Viewpoint Y: 2.0000
  Right Canvas/Viewpoint X: 0.0000
